// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt.Models;

namespace Projekt.Migrations
{
    [DbContext(typeof(NovenyContext))]
    partial class NovenyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("Projekt.Models.Betegseg", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipus")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Betegseg");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Tipus = "Anyagcsere"
                        },
                        new
                        {
                            ID = 2,
                            Tipus = "Általános"
                        },
                        new
                        {
                            ID = 3,
                            Tipus = "Bőr"
                        },
                        new
                        {
                            ID = 4,
                            Tipus = "Emésztőrendszer"
                        },
                        new
                        {
                            ID = 5,
                            Tipus = "Idegrendszer"
                        },
                        new
                        {
                            ID = 6,
                            Tipus = "Immunrendszer"
                        },
                        new
                        {
                            ID = 7,
                            Tipus = "Keringési rendszer"
                        },
                        new
                        {
                            ID = 8,
                            Tipus = "Légzőszervek"
                        },
                        new
                        {
                            ID = 9,
                            Tipus = "Mozgásszervek"
                        },
                        new
                        {
                            ID = 10,
                            Tipus = "Nemiszervek"
                        },
                        new
                        {
                            ID = 11,
                            Tipus = "Vizeletkiválasztó"
                        });
                });

            modelBuilder.Entity("Projekt.Models.Elofordulas", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Honap")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Elofordulas");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Honap = "január"
                        },
                        new
                        {
                            ID = 2,
                            Honap = "február"
                        },
                        new
                        {
                            ID = 3,
                            Honap = "március"
                        },
                        new
                        {
                            ID = 4,
                            Honap = "április"
                        },
                        new
                        {
                            ID = 5,
                            Honap = "május"
                        },
                        new
                        {
                            ID = 6,
                            Honap = "június"
                        },
                        new
                        {
                            ID = 7,
                            Honap = "július"
                        },
                        new
                        {
                            ID = 8,
                            Honap = "augusztus"
                        },
                        new
                        {
                            ID = 9,
                            Honap = "szeptember"
                        },
                        new
                        {
                            ID = 10,
                            Honap = "október"
                        },
                        new
                        {
                            ID = 11,
                            Honap = "november"
                        },
                        new
                        {
                            ID = 12,
                            Honap = "december"
                        });
                });

            modelBuilder.Entity("Projekt.Models.Felhasznalas", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Betegseg_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Elo_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gyujtott_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("Betegseg_ID");

                    b.HasIndex("Elo_Id");

                    b.HasIndex("Gyujtott_id");

                    b.ToTable("Felhasznalas");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Betegseg_ID = 1,
                            Elo_Id = 8,
                            Gyujtott_id = 3
                        },
                        new
                        {
                            ID = 2,
                            Betegseg_ID = 2,
                            Elo_Id = 8,
                            Gyujtott_id = 2
                        },
                        new
                        {
                            ID = 3,
                            Betegseg_ID = 3,
                            Elo_Id = 9,
                            Gyujtott_id = 2
                        },
                        new
                        {
                            ID = 4,
                            Betegseg_ID = 4,
                            Elo_Id = 7,
                            Gyujtott_id = 3
                        },
                        new
                        {
                            ID = 5,
                            Betegseg_ID = 5,
                            Elo_Id = 3,
                            Gyujtott_id = 3
                        },
                        new
                        {
                            ID = 6,
                            Betegseg_ID = 6,
                            Elo_Id = 1,
                            Gyujtott_id = 4
                        },
                        new
                        {
                            ID = 7,
                            Betegseg_ID = 7,
                            Elo_Id = 9,
                            Gyujtott_id = 4
                        },
                        new
                        {
                            ID = 8,
                            Betegseg_ID = 8,
                            Elo_Id = 3,
                            Gyujtott_id = 5
                        },
                        new
                        {
                            ID = 9,
                            Betegseg_ID = 9,
                            Elo_Id = 7,
                            Gyujtott_id = 5
                        },
                        new
                        {
                            ID = 10,
                            Betegseg_ID = 10,
                            Elo_Id = 4,
                            Gyujtott_id = 3
                        },
                        new
                        {
                            ID = 11,
                            Betegseg_ID = 11,
                            Elo_Id = 9,
                            Gyujtott_id = 3
                        });
                });

            modelBuilder.Entity("Projekt.Models.Gyujtott", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resz")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Gyujtott");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Resz = "Bogyó"
                        },
                        new
                        {
                            ID = 2,
                            Resz = "Virág"
                        },
                        new
                        {
                            ID = 3,
                            Resz = "Levél"
                        },
                        new
                        {
                            ID = 4,
                            Resz = "Gyökér"
                        },
                        new
                        {
                            ID = 5,
                            Resz = "Szár"
                        },
                        new
                        {
                            ID = 6,
                            Resz = "Termés"
                        });
                });

            modelBuilder.Entity("Projekt.Models.Novenyek", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Felh_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Informacio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kep")
                        .HasColumnType("TEXT");

                    b.Property<string>("Latin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Magyar")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("Felh_Id");

                    b.ToTable("Novenyek");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Felh_Id = 1,
                            Informacio = "Tekintettel a fekete áfonyában található számos antioxidáns hatóanyagra, nem meglepő, hogy a kutatások során kimutatták, hogy a szervezet számára fokozott antioxidáns védelmet biztosít az oxidatív stresszel szemben, többek közt a szív- és érrendszer tekintetében.De ami meglepő a fekete áfonyával kapcsolatos kutatások eredményei közt,hogy hatását az egész testre kifejti.Nemcsak a keringési rendszer az,melyről kimutatták, hogy a fekete áfonya fogyasztásával erősödik az antioxidáns védelme.",
                            Kep = "afonya.jpg",
                            Latin = "Vaccinium myrtillus",
                            Magyar = "Fekete áfonya"
                        },
                        new
                        {
                            ID = 2,
                            Felh_Id = 2,
                            Informacio = "A virágból készült tea vízhajtó, emésztést elősegítő, köhögéscsillapító hatású. Megfázásra, hörghurutra, izzasztószerként és immunrendszeri serkentőként használják. A friss bodzahajtás erős hashajtó. Használják még vértisztításra, fülfájásra, rekedtségre. A bogyó izzasztó, nagy mennyiségben hashajtó, ödéma és reuma ellen ajánljuk. Friss leve vagy a belőle készült lekvár bizonyítottan kitűnő szer a TBC gyógyítására. A bodzafa kérge purgáló, féreghajtó hatású. Erős vízhajtó, heveny vesegyulladásra, általános ödémásodásra ajánlják.",
                            Kep = "bodza.jpg",
                            Latin = "Sambucus",
                            Magyar = "Bodza"
                        },
                        new
                        {
                            ID = 3,
                            Felh_Id = 3,
                            Informacio = "Az erdei borostyán (Hedera helix) kúszó növekedésű, örökzöld növény, mely Európa nagy részén, valamint Délnyugat-Ázsiában is őshonos.Kiválóan alkalmas kerítések, épületek, fák, befuttatására, valamint talajtakaró növényként is megállja a helyét, mivel támaszték híján a talajt fedi be.Levélzetét karéjos levelek alkotják, melyek a fajtától függően egyszínű zöldek, valamint többszínű, mintásak is lehetnek. Ernyős virágzata kicsi, zöldessárga virágokból áll, melyek késő nyáron és kora ősszel nyílnak.Virágai nektárban gazdagok, méheket és más rovarokat vonzanak a kertbe. ",
                            Kep = "borostyan.jpg",
                            Latin = "Hedera helix",
                            Magyar = "Borostyán"
                        },
                        new
                        {
                            ID = 4,
                            Felh_Id = 4,
                            Informacio = "Máriatövist már régóta használják a természetes gyógyításban és akik használják, azt állítják, hogy sokkal egészségesebbek. Tavasszal és ősszel frissen is hozzájuthatunk, a növény kivonatával erősíthetjük a májunkat és megvédhetjük legfontosabb méregtelenítő szervünket a sejtekbe jutó toxinok káros hatásaitól, mivel azokat eltávolítja és feldolgozza. A máriatövisnek antidepresszáns hatása is van, segít mozgósítani a máj stagnáló energiáit. A máriatövis megnyugtatja és nedvesíti a nyálkahártyákat, így gyógyír lehet a vese, a húgyhólyag és a bőrgyulladások számára.",
                            Kep = "maria.jpg",
                            Latin = "Silybum marianum",
                            Magyar = "Máriatövis"
                        },
                        new
                        {
                            ID = 5,
                            Felh_Id = 5,
                            Informacio = "A páfrányok ideális szobanövények, melyek már évtizedek óta kedvenceink. A páfrányok csoportjából a szobapáfrány (Nephrolepis) a legismertebb. Sokoldalú növények, melyek egyben gondoskodnak az egészséges klímáról is otthonában azzal, hogy tisztítják a levegőt és megfelelő páratartalmat teremtenek. Mivel a páfrányok, mint szobanövények eredetileg a (szub)trópusi területekről származnak, a magas páratartalmat kedvelik. Ebből kifolyólag ideálisak lehetnek fürdőszobai növénynek.",
                            Kep = "pafrany.jpg",
                            Latin = "Ginkgo biloba",
                            Magyar = "Páfrányfenyő"
                        },
                        new
                        {
                            ID = 6,
                            Felh_Id = 6,
                            Informacio = "A ginzenget Ázsiában és Észak-Amerikában már évszázadok óta használják a gyógyászatban. A legtöbben az agyműködés serkentésére, a koncentráció növelésére, a szellemi és fizikai állóképesség javítására alkalmazzák. A ginseng (ginzeng) segítségével a depresszió, a szorongás és a krónikus fáradtság is természetes módon kezelhető.",
                            Kep = "ginzeng.jpg",
                            Latin = "Panax",
                            Magyar = "Ginzeng"
                        },
                        new
                        {
                            ID = 7,
                            Felh_Id = 7,
                            Informacio = "A fokhagyma antibakteriális és antimikotikus (gombaellenes) hatása révén légúti megbetegedések és a Candida albicans okozta fertőzések kezelésében használatos. Továbbá tágítja az ereket is. Rendszeres, kúraszerű alkalmazása csökkenti a vér káros LDL-koleszterin-szintjét, antioxidánsként serkenti az immunrendszert, csökkenti a mellkasi fertőzéseket, véralvadásgátló- és vérnyomáscsökkentő.",
                            Kep = "fokhagyma.jpg",
                            Latin = "Alii sativi bulbus",
                            Magyar = "Fokhagyma"
                        },
                        new
                        {
                            ID = 8,
                            Felh_Id = 8,
                            Informacio = "Elsősorban veseműködés javítására szolgál, vízhajtó hatása kísérletileg igazolt. Vesekövet, vesehomokot lehet vele elhajtani, mindenféle húgyúti fertőzést megszüntetni.Szilícium és szerves ásvány tartalma miatt kiváló tonizáló, erősítő hatású. A romák salátaként fogyasztják zsenge termőhajtásait ebből a célból. Csontok, köröm erősítésére is használjuk. Csontritkulás esetén porrá őrölve kell fogyasztani. Jó vérzéscsillapító orrvérzés, tüdővérzés, bőséges havivérzés esetén.",
                            Kep = "zsurlo.jpg",
                            Latin = "Equisetum arvense",
                            Magyar = "Mezei zsurló"
                        },
                        new
                        {
                            ID = 9,
                            Felh_Id = 9,
                            Informacio = "Diétázás nélkül is csökkenti a testsúlyt, normalizálja a vérnyomást, mérsékli az ízületi gyulladást, lassítja a sclerosis multiplex előrehaladását, enyhíti a másnaposságot.Segíti a bőr megújulási folyamatát. Enyhíti a menstruációs panaszokat. Szerepet játszik a vér koleszterinszintjének csökkentésében. A kozmetikaipar a száraz, gyulladt bőr ápolására alkalmazható szereket készít belőle.",
                            Kep = "ligetszepe.jpg",
                            Latin = "Oenothera biennis",
                            Magyar = "Ligetszépe"
                        },
                        new
                        {
                            ID = 10,
                            Felh_Id = 10,
                            Informacio = "Csak hazánkban nyolc különböző palástfűfajt ismerünk, amelyek küllemükben és gyógyhatásukban is nagyon hasonlóak, a név tehát gyűjtőfogalom. A rózsafélék (Rosaceae) családjába tartozó, évelő növény. Gyöktörzse fejlett, ezzel vészeli át a telet.Szára a termőhelytől függően a földön heverőtől az 50 cm magasig változhat.",
                            Kep = "palastfu.jpg",
                            Latin = "Alchemilla monticola",
                            Magyar = "Palástfű"
                        },
                        new
                        {
                            ID = 11,
                            Felh_Id = 11,
                            Informacio = "A medveszőlő egy rendkívül különleges megjelenésű örökzöld növény, melynek élénkpiros termése leginkább a vörös áfonyára hasonlít. A növény levelét és leveles hajtásait lehet hasznosítani gyógyászati célokra, például tea vagy borogatás készítésére.Számos jótékony hatással rendelkezik. Eredményesen kezelhetőek vele a húgyúti megbetegedések, a nőgyógyászati problémák, a magas vérnyomás és a hasmenés, de elősegítheti a sebgyógyulást is. ",
                            Kep = "medveszolo.jpg",
                            Latin = "Uvae ursi folium",
                            Magyar = "Medveszőlő levél"
                        });
                });

            modelBuilder.Entity("Projekt.Models.Felhasznalas", b =>
                {
                    b.HasOne("Projekt.Models.Betegseg", "Betegseg")
                        .WithMany()
                        .HasForeignKey("Betegseg_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projekt.Models.Elofordulas", "Elofordulas")
                        .WithMany()
                        .HasForeignKey("Elo_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projekt.Models.Gyujtott", "Gyujtott")
                        .WithMany()
                        .HasForeignKey("Gyujtott_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Betegseg");

                    b.Navigation("Elofordulas");

                    b.Navigation("Gyujtott");
                });

            modelBuilder.Entity("Projekt.Models.Novenyek", b =>
                {
                    b.HasOne("Projekt.Models.Felhasznalas", "Felhasznalas")
                        .WithMany()
                        .HasForeignKey("Felh_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Felhasznalas");
                });
#pragma warning restore 612, 618
        }
    }
}
